//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.IOBM.MobileManager.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvancedSearchMap
    {
        public int pkAdvancedSearchMapID { get; set; }
        public string FromEntity { get; set; }
        public string ToEntity { get; set; }
    }
}
