//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.IOBM.MobileManager.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvancedSearchField
    {
        public int pkAdvancedSearchField { get; set; }
        public int enSearchCategory { get; set; }
        public string EntityName { get; set; }
        public string ColumnName { get; set; }
        public string DisplayName { get; set; }
        public string DataType { get; set; }
        public string ControlType { get; set; }
        public string OtherEntityColumnName { get; set; }
        public string FinalEntityColumnName { get; set; }
    }
}
