//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.IOBM.MobileManager.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataImportProperty
    {
        public int pkDataImportPropertyID { get; set; }
        public int enDataEntity { get; set; }
        public string PropertyDescription { get; set; }
        public string PropertyName { get; set; }
        public bool MultipleProperty { get; set; }
        public bool Required { get; set; }
        public bool ExistingClientRequired { get; set; }
    }
}
