//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.IOBM.MobileManager.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataImportSearchProperty
    {
        public int pkDataImportSearchPropertyID { get; set; }
        public int enDataEntity { get; set; }
        public string SearchProperties { get; set; }
    }
}
