//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.IOBM.MobileManager.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.DeviceIMENumbers = new HashSet<DeviceIMENumber>();
        }
    
        public int pkDeviceID { get; set; }
        public int fkContractID { get; set; }
        public int fkDeviceMakeID { get; set; }
        public int fkDeviceModelID { get; set; }
        public int fkStatusID { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime ReceiveDate { get; set; }
        public Nullable<decimal> InsuranceCost { get; set; }
        public Nullable<decimal> InsuranceValue { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual DeviceMake DeviceMake { get; set; }
        public virtual DeviceModel DeviceModel { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceIMENumber> DeviceIMENumbers { get; set; }
    }
}
