//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.IOBM.MobileManager.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceSimCard
    {
        public int pkDeviceSimCardD { get; set; }
        public int fkDeviceID { get; set; }
        public int fkSimCardID { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual SimCard SimCard { get; set; }
    }
}
