//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gijima.IOBM.MobileManager.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimCard
    {
        public int pkSimCardID { get; set; }
        public Nullable<int> fkContractID { get; set; }
        public Nullable<int> fkStatusID { get; set; }
        public string CellNumber { get; set; }
        public string CardNumber { get; set; }
        public string PinNumber { get; set; }
        public string PUKNumber { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Status Status { get; set; }
    }
}
